spring.application.name=auth-service
server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/medibook_auth_db

jwt.secret=MySuperSecretKeyForMedibookAuthServiceMySuperSecretKey
jwt.expiration=86400000

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis